![sql](img/sql-logo.jpg)

# A beginner's guide to databases, SQL, & using them with `pandas`

**Scenario:** You are a data analyst for the Homeland Security, trying to create reports on the active airports world wide. The data you need to access is in a SQL database. YOu need to be able to query for the data in a database!

## Learning goals:
- Goal 1: Summarize the use case for sql in the data science skill set
- Goal 2: Define key sql terminology
- Goal 3: Get information about DB schema and table structure
- Goal 4: Use basic SQL commands:
    - Construct SQL queries
    - Use JOIN to merge tables along logical columns
    - Grouping Data with SQL
- Goal 5: Query data from pandas dataframes using SQL
- Goal 6: Convert SQL to pandas

## Goal 1: Summarize

To date the data we've seen has looked like [this.](https://data.austintexas.gov/Health-and-Community-Services/Austin-Animal-Center-Intakes/wter-evkm)

That is how we need data to look to run analysis and build models.<br>
But it doesn't _live_ there in it's native state.

[Netflix has a great article](https://medium.com/netflix-techblog/notebook-innovation-591ee3221233) describing three different data roles at their company, their different needs, and their toolsets.

![netflix](img/netflix-data-roles.jpeg)

Examining that graphic, SQL shows up as one of the tools of the _Data Engineer_

Data Engineers provide the essential data architecture services that make data science possible.

![hierarchy](img/ai-hierachy.png)

[Source: Monica Rogati’s fantastic Medium post “The AI Hierarchy of Needs”
](https://hackernoon.com/the-ai-hierarchy-of-needs-18f111fcc007)

## What does it mean to **Engineer Data**?

Let's start with a basic scenario:<br>
You are HR. You have *no* current database. 
How would you set it up?

Data needs considerations:
- What you want to store
- What "views" you anticipate wanting in the future

Structure considerations:
- Speed of retrieval
- How much data you are accessing
- How much you are storing

![etl](img/etl.png)

[img source: Jeff Hammerbacher’s slide from UC Berkeley CS 194 course ](https://bcourses.berkeley.edu/courses/1377158/pages/cs-194-16-introduction-to-data-science-fall-2015)

### What is a Relational Database? 

![rdb](img/relational-dbms-model.png)
[reference for image ](https://www.studytonight.com/dbms/database-model.php)

### POPULAR RDBMS

- SQLite
- MySQL
- PostgreSql
- Oracle DB
- SQL Server

***
### SQL

[History of SQL](https://www.businessnewsdaily.com/5804-what-is-sql.html)

> Future users of large data banks must be protected from having to know how the data is organized in the machine (the internal representation). A prompting service which supplies such information is not a satisfactory solution. Activities of users at terminals and most application programs should remain unaffected when the internal representation of data is changed and even when some aspects of the external representation are changed. Changes in data representation will often be needed as a result of changes in query, update, and report traffic and natural growth in the types of stored information.
.
.
.<br>
<br>
In Section 1 a relational model of data is proposed as a basis for protecting users of formatted data systems from the potentially disruptive changes in data representation caused by growth in the data bank and changes in traffic.

[The original SQL paper from the 1970s.](https://www.seas.upenn.edu/~zives/03f/cis550/codd.pdf)

***
## Goal 2: Database terminology

### Relational Database Schema

![schema](img/MySQL_Schema_Music_Example.png)

[source of image](https://database.guide/what-is-a-database-schema/)

### Table columns view
<img src="img/columns.png" width=650>

### Terminology

- Database
- Schema
- Queries
- Tables
- Views
- Primary Keys
- Foreign Keys
- Indexes
- Functions & User Defined Functions (UDFs)

***
### SQLite

<img src="img/SQLite-Python.jpg" width=650>

"SQLite is a C library that provides a lightweight disk-based database that doesn’t require a separate server process and allows accessing the database using a nonstandard variant of the SQL query language. Some applications can use SQLite for internal data storage. It’s also possible to prototype an application using SQLite and then port the code to a larger database such as PostgreSQL or Oracle." - [sqlite documentation](https://docs.python.org/2/library/sqlite3.html)

## But what about connecting to database servers?

To connect to other database types there are many different libraries:
- Oracle: [cx_Oracle](https://oracle.github.io/python-cx_Oracle/)
- MySQL: [MySQL-python](https://github.com/farcepest/MySQLdb1)
- PostgreSQL: [Psycopg2](http://initd.org/psycopg/docs/)
- Microsoft SQL Server: [pymssql](http://www.pymssql.org/en/stable/)

These all implement [PEP 249: DB API v2](https://www.python.org/dev/peps/pep-0249/)

***
## Goal 3: Get going with sqlite!

In [5]:
import sqlite3

#### Load a DB object with `connect` and `cursor`

In [2]:
con = sqlite3.connect('data/flights.db')
cursor = con.cursor()

#### Use sqlite_master to find all the tables in the schema
Get the schema of a database from a db in sqlite

In [3]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('airports',), ('airlines',), ('routes',)]

In [4]:
cursor.description

(('name', None, None, None, None, None, None),)

In [5]:
cursor.execute("SELECT name, type FROM sqlite_master;")
print(cursor.fetchall())

[('airports', 'table'), ('ix_airports_index', 'index'), ('airlines', 'table'), ('ix_airlines_index', 'index'), ('routes', 'table'), ('ix_routes_index', 'index')]

In [7]:
print(cursor.fetchone()) # at the end of database cursor needs a new SQL query

None

In [8]:
cursor.description

(('name', None, None, None, None, None, None),
 ('type', None, None, None, None, None, None))

In [14]:
cursor.execute("SELECT * FROM sqlite_master;")
results = cursor.fetchall()
for res in results:
    print(res)

('table', 'airports', 'airports', 2, 'CREATE TABLE airports (\n[index] INTEGER,\n  [id] TEXT,\n  [name] TEXT,\n  [city] TEXT,\n  [country] TEXT,\n  [code] TEXT,\n  [icao] TEXT,\n  [latitude] TEXT,\n  [longitude] TEXT,\n  [altitude] TEXT,\n  [offset] TEXT,\n  [dst] TEXT,\n  [timezone] TEXT\n)')
('index', 'ix_airports_index', 'airports', 3, 'CREATE INDEX ix_airports_index ON airports ([index])')
('table', 'airlines', 'airlines', 945, 'CREATE TABLE airlines (\n[index] INTEGER,\n  [id] TEXT,\n  [name] TEXT,\n  [alias] TEXT,\n  [iata] TEXT,\n  [icao] TEXT,\n  [callsign] TEXT,\n  [country] TEXT,\n  [active] TEXT\n)')
('index', 'ix_airlines_index', 'airlines', 946, 'CREATE INDEX ix_airlines_index ON airlines ([index])')
('table', 'routes', 'routes', 1393, 'CREATE TABLE routes (\n[index] INTEGER,\n  [airline] TEXT,\n  [airline_id] TEXT,\n  [source] TEXT,\n  [source_id] TEXT,\n  [dest] TEXT,\n  [dest_id] TEXT,\n  [codeshare] TEXT,\n  [stops] TEXT,\n  [equipment] TEXT\n)')
('index', 'ix_routes_index', 'routes', 1394, 'CREATE INDEX ix_routes_index ON routes ([index])')

#### Get information about one table

**A note about** `execute`<br>
Each time you use it, you reset the value of cursor

In [9]:
cursor.execute("SELECT * FROM airports as a").fetchone()

(0,
 '1',
 'Goroka',
 'Goroka',
 'Papua New Guinea',
 'GKA',
 'AYGA',
 '-6.081689',
 '145.391881',
 '5282',
 '10',
 'U',
 'Pacific/Port_Moresby')

In [10]:
cursor.fetchone()

(1,
 '2',
 'Madang',
 'Madang',
 'Papua New Guinea',
 'MAG',
 'AYMD',
 '-5.207083',
 '145.7887',
 '20',
 '10',
 'U',
 'Pacific/Port_Moresby')

In [11]:
cursor.fetchmany(4)

[(2,
  '3',
  'Mount Hagen',
  'Mount Hagen',
  'Papua New Guinea',
  'HGU',
  'AYMH',
  '-5.826789',
  '144.295861',
  '5388',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (3,
  '4',
  'Nadzab',
  'Nadzab',
  'Papua New Guinea',
  'LAE',
  'AYNZ',
  '-6.569828',
  '146.726242',
  '239',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (4,
  '5',
  'Port Moresby Jacksons Intl',
  'Port Moresby',
  'Papua New Guinea',
  'POM',
  'AYPY',
  '-9.443383',
  '147.22005',
  '146',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (5,
  '6',
  'Wewak Intl',
  'Wewak',
  'Papua New Guinea',
  'WWK',
  'AYWK',
  '-3.583828',
  '143.669186',
  '19',
  '10',
  'U',
  'Pacific/Port_Moresby')]

#### Use description

In [12]:
cursor.description

(('index', None, None, None, None, None, None),
 ('id', None, None, None, None, None, None),
 ('name', None, None, None, None, None, None),
 ('city', None, None, None, None, None, None),
 ('country', None, None, None, None, None, None),
 ('code', None, None, None, None, None, None),
 ('icao', None, None, None, None, None, None),
 ('latitude', None, None, None, None, None, None),
 ('longitude', None, None, None, None, None, None),
 ('altitude', None, None, None, None, None, None),
 ('offset', None, None, None, None, None, None),
 ('dst', None, None, None, None, None, None),
 ('timezone', None, None, None, None, None, None))

#### Or use `Pragma`
`Pragma` tool [link here](https://www.sqlite.org/pragma.html#pragma_table_info)

**output**<br>
`(column id, column name, data type, whether or not the column can be NULL, and the default value for the column)`

In [13]:
cursor.execute("PRAGMA table_info(airports)")
info = cursor.fetchall()
print(*info, sep = "\n")

(0, 'index', 'INTEGER', 0, None, 0)
(1, 'id', 'TEXT', 0, None, 0)
(2, 'name', 'TEXT', 0, None, 0)
(3, 'city', 'TEXT', 0, None, 0)
(4, 'country', 'TEXT', 0, None, 0)
(5, 'code', 'TEXT', 0, None, 0)
(6, 'icao', 'TEXT', 0, None, 0)
(7, 'latitude', 'TEXT', 0, None, 0)
(8, 'longitude', 'TEXT', 0, None, 0)
(9, 'altitude', 'TEXT', 0, None, 0)
(10, 'offset', 'TEXT', 0, None, 0)
(11, 'dst', 'TEXT', 0, None, 0)
(12, 'timezone', 'TEXT', 0, None, 0)

#### Making fetch happen

`.fetchall()` is how you get the query results out of the object.

You can also `.fetchone()` or `.fetchmany()`

**Task:** Get the descriptive data for airlines and routes tables

In [15]:
cursor.execute("PRAGMA table_info(airlines)")
info = cursor.fetchall()
print(*info, sep = "\n")

(0, 'index', 'INTEGER', 0, None, 0)
(1, 'id', 'TEXT', 0, None, 0)
(2, 'name', 'TEXT', 0, None, 0)
(3, 'alias', 'TEXT', 0, None, 0)
(4, 'iata', 'TEXT', 0, None, 0)
(5, 'icao', 'TEXT', 0, None, 0)
(6, 'callsign', 'TEXT', 0, None, 0)
(7, 'country', 'TEXT', 0, None, 0)
(8, 'active', 'TEXT', 0, None, 0)

In [16]:
cursor.execute("PRAGMA table_info(routes)")
info = cursor.fetchall()
print(*info, sep = "\n")

(0, 'index', 'INTEGER', 0, None, 0)
(1, 'airline', 'TEXT', 0, None, 0)
(2, 'airline_id', 'TEXT', 0, None, 0)
(3, 'source', 'TEXT', 0, None, 0)
(4, 'source_id', 'TEXT', 0, None, 0)
(5, 'dest', 'TEXT', 0, None, 0)
(6, 'dest_id', 'TEXT', 0, None, 0)
(7, 'codeshare', 'TEXT', 0, None, 0)
(8, 'stops', 'TEXT', 0, None, 0)
(9, 'equipment', 'TEXT', 0, None, 0)

***
## Goal 4: Use basic SQL commands 
- Construct SQL queries
- Use JOIN to merge tables along logical columns
- Grouping Data with SQL

### Construct SQL queries

**Select**

**From**

**Where**

**Order by**

**Limit**

#### Options for each:

**Select**:  `distinct`, using `as` to rename columns, single number aggregates

**From:** also uses aliasing with `as`

**Where**: equals is only one `=`, `between`, `in`, wildcards `%`, `AND`, `OR`, `NOT`

**Order by**: `asc` and `desc`

**Limit**:  #

**Task**: 
- Select only active airlines in the UK from the airlines table
- Select the unique list of countries with airports

In [17]:
cursor.execute("""
SELECT name
FROM airlines
WHERE active = 'Y'
  AND country = 'United Kingdom';
""")
cursor.fetchmany(5)

[('Astraeus',),
 ('Air Southwest',),
 ('Aurigny Air Services',),
 ('Air Wales',),
 ('AD Aviation',)]

In [5]:
statement = """ -- Select the unique list of countries with airports
            SELECT DISTINCT country -- DISTINCT is on a row unique level
            FROM airports
            WHERE country LIKE 'G%' -- capitalization doesn't matter in SQLite
            """
cursor.execute(statement)
print(*cursor.fetchall(),sep='\n')

('Greenland',)
('Ghana',)
('Germany',)
('Guernsey',)
('Gabon',)
('Gambia',)
('Guinea-Bissau',)
('Guinea',)
('Greece',)
('Gibraltar',)
('Guatemala',)
('Guam',)
('Guyana',)
('Guadeloupe',)
('Grenada',)
('Georgia',)

### SQL Joins

SQL joins can be used to both **add** data to a table and **remove** data from a table.

<img src="img/venn.png" width=550>

**Task** Write a query that will join the latitude and longitude data from the airports table to the information on the routes table

In [9]:
cursor.execute("""
SELECT DISTINCT r.source, r.dest, a.latitude, a.longitude 
    FROM airports a -- aliasing
    JOIN routes r
        ON a.id = r.source_id -- "USING" without writing "A.key = B.key"
""")
print(*cursor.fetchall(), sep='\n')

('GKA', '-6.081689', '145.391881')
('MAG', '-5.207083', '145.7887')
('HGU', '-5.826789', '144.295861')
('LAE', '-6.569828', '146.726242')
('POM', '-9.443383', '147.22005')
('WWK', '-3.583828', '143.669186')
('UAK', '61.160517', '-45.425978')
('GOH', '64.190922', '-51.678064')
('SFJ', '67.016969', '-50.689325')
('THU', '76.531203', '-68.703161')
('AEY', '65.659994', '-18.072703')
('EGS', '65.283333', '-14.401389')
('IFJ', '66.058056', '-23.135278')
('KEF', '63.985', '-22.605556')
('RKV', '64.13', '-21.940556')
('YAM', '46.485001', '-84.509445')
('YAY', '51.391944', '-56.083056')
('YBC', '49.1325', '-68.204444')
('YBG', '48.330555', '-70.996391')
('YBK', '64.298889', '-96.077778')
('YBL', '49.950832', '-125.270833')
('YBR', '49.91', '-99.951944')
('YCB', '69.108055', '-105.138333')
('YCD', '49.052333', '-123.870167')
('YCG', '49.296389', '-117.6325')
('YCL', '47.990833', '-66.330278')
('YCO', '67.816667', '-115.143889')
('YCY', '70.486111', '-68.516667')
('YZS', '64.193333', '-83.359444')
('YDF', '49.210833', '-57.391388')
('YDQ', '55.742333', '-120.183')
('YEG', '53.309723', '-113.579722')
('YEK', '61.094166', '-94.070833')
('YEV', '68.304167', '-133.482778')
('YFB', '63.75639', '-68.555832')
('YFC', '45.868889', '-66.537222')
('YFO', '54.678055', '-101.681667')
('YFS', '61.760153', '-121.236525')
('YGK', '44.225277', '-76.596944')
('YGL', '53.625278', '-77.704167')
('YGP', '48.775278', '-64.478611')
('YGR', '47.424721', '-61.778056')
('YHD', '49.831667', '-92.744167')
('YHI', '70.762778', '-117.806111')
('YHK', '68.635556', '-95.849722')
('YHM', '43.173611', '-79.935')
('YHU', '45.5175', '-73.416944')
('YHY', '60.839722', '-115.782778')
('YHZ', '44.880833', '-63.50861')
('YIO', '72.683334', '-77.966667')
('YJT', '48.544167', '-58.549999')
('YKA', '50.702222', '-120.444444')
('YKF', '43.460833', '-80.378611')
('YKL', '54.805278', '-66.805278')
('YLL', '53.309166', '-110.0725')
('YLW', '49.956112', '-119.377778')
('YMM', '56.653333', '-111.221944')
('YMO', '51.291111', '-80.607778')
('YNA', '50.19', '-61.789167')
('YOJ', '58.621389', '-117.164722')
('YOW', '45.3225', '-75.669167')
('YPL', '51.446388', '-90.214167')
('YPN', '49.836389', '-64.288611')
('YPR', '54.28611', '-130.444722')
('YPY', '58.767223', '-111.117222')
('YQB', '46.791111', '-71.393333')
('YQF', '52.182222', '-113.894444')
('YQG', '42.275556', '-82.955556')
('YQK', '49.788334', '-94.363056')
('YQL', '49.630278', '-112.799722')
('YQM', '46.112221', '-64.678611')
('YQQ', '49.710833', '-124.886667')
('YQR', '50.431944', '-104.665833')
('YQT', '48.371944', '-89.323889')
('YQU', '55.179722', '-118.885')
('YQX', '48.936944', '-54.568056')
('YQY', '46.161388', '-60.047779')
('YQZ', '53.026112', '-122.510278')
('YRB', '74.716944', '-94.969444')
('YRT', '62.81139', '-92.115833')
('YSB', '46.625', '-80.798889')
('YSJ', '45.316111', '-65.890278')
('YSM', '60.020278', '-111.961944')
('YSY', '71.993889', '-125.2425')
('YTE', '64.23', '-76.526667')
('YTH', '55.801111', '-97.864166')
('YTS', '48.569721', '-81.376667')
('YTZ', '43.627499', '-79.396167')
('YUB', '69.433334', '-133.026389')
('YUL', '45.470556', '-73.740833')
('YUT', '66.521389', '-86.224722')
('YUX', '68.776111', '-81.243611')
('YUY', '48.206111', '-78.835556')
('YVM', '67.545833', '-64.031389')
('YVO', '48.053333', '-77.782778')
('YVP', '58.096111', '-68.426944')
('YVQ', '65.281617', '-126.798219')
('YVR', '49.193889', '-123.184444')
('YWG', '49.910036', '-97.239886')
('YWK', '52.921944', '-66.864444')
('YWL', '52.183056', '-122.054167')
('YXC', '49.612222', '-115.781944')
('YXE', '52.170834', '-106.699722')
('YXH', '50.01889', '-110.720833')
('YXJ', '56.238056', '-120.740278')
('YXL', '50.113889', '-91.905278')
('YXP', '66.145', '-65.713611')
('YXS', '53.889444', '-122.678889')
('YXT', '54.468508', '-128.576219')
('YXU', '43.033056', '-81.151111')
('YXX', '49.025278', '-122.360556')
('YXY', '60.709553', '-135.067269')
('YYB', '46.363611', '-79.422778')
('YYC', '51.113888', '-114.020278')
('YYD', '54.824722', '-127.182778')
('YYE', '58.836389', '-122.596944')
('YYF', '49.463056', '-119.602222')
('YYG', '46.290001', '-63.121111')
('YYH', '69.546667', '-93.576667')
('YYJ', '48.646944', '-123.425833')
('YYQ', '58.739167', '-94.065')
('YYR', '53.319168', '-60.425833')
('YYT', '47.61861', '-52.751945')
('YYU', '49.413889', '-82.4675')
('YYY', '48.608612', '-68.208056')
('YYZ', '43.677223', '-79.630556')
('YZF', '62.462778', '-114.440278')
('YZP', '53.254333', '-131.813833')
('YZR', '42.999444', '-82.308889')
('YZT', '50.680556', '-127.366667')
('YZV', '50.223333', '-66.265556')
('ZFM', '67.4075', '-134.860556')
('BJA', '36.711997', '5.069922')
('ALG', '36.691014', '3.215408')
('DJG', '24.292767', '9.452444')
('TMR', '22.811461', '5.451075')
('AAE', '36.822225', '7.809167')
('CZL', '36.276028', '6.620386')
('TEE', '35.431611', '8.120717')
('HRM', '32.930431', '3.311542')
('TID', '35.341136', '1.463147')
('TLM', '35.016667', '-1.45')
('ORN', '35.623858', '-0.621183')
('MUW', '35.207725', '0.147142')
('AZR', '27.837589', '-0.186414')
('BSK', '34.793289', '5.738231')
('ELG', '30.571294', '2.859586')
('GHA', '32.384106', '3.794114')
('HME', '31.672972', '6.140444')
('INZ', '27.251022', '2.512017')
('TGR', '33.067803', '6.088672')
('OGX', '31.917223', '5.412778')
('IAM', '28.05155', '9.642911')
('COO', '6.357228', '2.384353')
('OUA', '12.353194', '-1.512417')
('BOY', '11.160056', '-4.330969')
('ACC', '5.605186', '-0.166786')
('TML', '9.557192', '-0.863214')
('NYI', '7.361828', '-2.328756')
('TKD', '4.896056', '-1.774756')
('ABJ', '5.261386', '-3.926294')
('ABV', '9.006792', '7.263172')
('BNI', '6.316981', '5.599503')
('CBQ', '4.976019', '8.347197')
('ENU', '6.474272', '7.561961')
('IBA', '7.362458', '3.978333')
('ILR', '8.440211', '4.493919')
('JOS', '9.639828', '8.86905')
('KAD', '10.696025', '7.320114')
('KAN', '12.047589', '8.524622')
('LOS', '6.577369', '3.321156')
('PHC', '5.015494', '6.949594')
('SKO', '12.916322', '5.207189')
('YOL', '9.257553', '12.430422')
('NIM', '13.481547', '2.183614')
('MIR', '35.758056', '10.754722')
('TUN', '36.851033', '10.227217')
('GAF', '34.422022', '8.822503')
('GAE', '33.876919', '10.103333')
('DJE', '33.875031', '10.775461')
('SFA', '34.717953', '10.690972')
('TOE', '33.939722', '8.110556')
('LFW', '6.165611', '1.254511')
('ANR', '51.189444', '4.460278')
('BRU', '50.901389', '4.484444')
('CRL', '50.459197', '4.453817')
('LGG', '50.637417', '5.443222')
('OST', '51.198889', '2.862222')
('SXF', '52.380001', '13.5225')
('DRS', '51.132767', '13.767161')
('ERF', '50.979811', '10.958106')
('FRA', '50.026421', '8.543125')
('FMO', '52.134642', '7.684831')
('HAM', '53.630389', '9.988228')
('CGN', '50.865917', '7.142744')
('DUS', '51.289453', '6.766775')
('MUC', '48.353783', '11.786086')
('NUE', '49.4987', '11.066897')
('LEJ', '51.432447', '12.241633')
('SCN', '49.214553', '7.109508')
('STR', '48.689878', '9.221964')
('TXL', '52.559686', '13.287711')
('HAJ', '52.461056', '9.685078')
('BRE', '53.0475', '8.786667')
('HHN', '49.948672', '7.263892')
('MHG', '49.472706', '8.514264')
('XFW', '53.535886', '9.837025')
('LBC', '53.805367', '10.719222')
('PAD', '51.614089', '8.616317')
('DTM', '51.518314', '7.612242')
('AGB', '48.425158', '10.931764')
('FDH', '47.671317', '9.511486')
('KSF', '51.408394', '9.377631')
('GWT', '54.91325', '8.340472')
('URE', '58.229883', '22.509494')
('TLL', '59.413317', '24.832844')
('TAY', '58.307461', '26.690428')
('HEL', '60.317222', '24.963333')
('IVL', '68.607269', '27.405328')
('JOE', '62.662906', '29.60755')
('JYV', '62.399453', '25.678253')
('KEM', '65.781889', '24.5991')
('KAJ', '64.285472', '27.692414')
('KOK', '63.721172', '23.143131')
('KAO', '65.987575', '29.239381')
('KTT', '67.701022', '24.84685')
('KUO', '63.00715', '27.797756')
('LPP', '61.044553', '28.144397')
('MHQ', '60.122203', '19.898156')
('OUL', '64.930061', '25.354564')
('POR', '61.461686', '21.799983')
('RVN', '66.564822', '25.830411')
('SVL', '61.943064', '28.945136')
('TMP', '61.414147', '23.604392')
('TKU', '60.514142', '22.262808')
('VAA', '63.05065', '21.762175')
('BFS', '54.6575', '-6.215833')
('BHD', '54.618056', '-5.8725')
('LDY', '55.042778', '-7.161111')
('BHX', '52.453856', '-1.748028')
('GLO', '51.894167', '-2.167222')
('MAN', '53.353744', '-2.27495')
('NQY', '50.440558', '-4.995408')
('CWL', '51.396667', '-3.343333')
('BRS', '51.382669', '-2.719089')
('LPL', '53.333611', '-2.849722')
('LTN', '51.874722', '-0.368333')
('BOH', '50.78', '-1.8425')
('SOU', '50.950261', '-1.356803')
('ACI', '49.706111', '-2.214722')
('GCI', '49.434956', '-2.601969')
('JER', '49.207947', '-2.195508')
('LGW', '51.148056', '-0.190278')
('LCY', '51.505278', '0.055278')
('LHR', '51.4775', '-0.461389')
('SEN', '51.571389', '0.695556')
('BLK', '53.771667', '-3.028611')
('HUY', '53.574444', '-0.350833')
('LBA', '53.865897', '-1.660569')
('CEG', '53.178056', '-2.977778')
('IOM', '54.083333', '-4.623889')
('NCL', '55.0375', '-1.691667')
('MME', '54.509189', '-1.429406')
('EMA', '52.831111', '-1.328056')
('KOI', '58.957778', '-2.905')
('LSI', '59.878889', '-1.295556')
('WIC', '58.458889', '-3.093056')
('ABZ', '57.201944', '-2.197778')
('INV', '57.5425', '-4.0475')
('GLA', '55.871944', '-4.433056')
('EDI', '55.95', '-3.3725')
('ILY', '55.681944', '-6.256667')
('PIK', '55.509444', '-4.586667')
('BEB', '57.481111', '-7.362778')
('DND', '56.452499', '-3.025833')
('SYY', '58.215556', '-6.331111')
('TRE', '56.499167', '-6.869167')
('NWI', '52.675833', '1.282778')
('STN', '51.885', '0.235')
('EXT', '50.734444', '-3.413889')
('MPN', '-51.822777', '-58.447222')
('AMS', '52.308613', '4.763889')
('MST', '50.911658', '5.770144')
('EIN', '51.450139', '5.374528')
('GRQ', '53.11972', '6.579444')
('RTM', '51.956944', '4.437222')
('ORK', '51.841269', '-8.491111')
('DUB', '53.421333', '-6.270075')
('NOC', '53.910297', '-8.818492')
('KIR', '52.180878', '-9.523783')
('SNN', '52.701978', '-8.924817')
('WAT', '52.1872', '-7.086964')
('AAR', '56.300017', '10.619008')
('BLL', '55.740322', '9.151778')
('CPH', '55.617917', '12.655972')
('EBJ', '55.525942', '8.553403')
('KRP', '56.297458', '9.124628')
('RNN', '55.063267', '14.759558')
('SGD', '54.964367', '9.791731')
('FAE', '62.063628', '-7.277219')
('AAL', '57.092789', '9.849164')
('LUX', '49.626575', '6.211517')
('AES', '62.560372', '6.110164')
('ANX', '69.2925', '16.144167')
('ALF', '69.976111', '23.371667')
('BNN', '65.461111', '12.2175')
('BOO', '67.269167', '14.365278')
('BGO', '60.293386', '5.218142')
('BJF', '70.600278', '29.6925')
('KRS', '58.204214', '8.085369')
('BDU', '69.055758', '18.540356')
('EVE', '68.4913', '16.678108')
('VDB', '61.015556', '9.288056')
('FRO', '61.583611', '5.024722')
('OSL', '60.193917', '11.100361')
('HAU', '59.345267', '5.208364')
('HAA', '70.486675', '22.139744')
('KSU', '63.111781', '7.824522')
('KKN', '69.725781', '29.891295')
('MOL', '62.744722', '7.2625')
('MJF', '65.783997', '13.214914')
('LKL', '70.068814', '24.973489')
('OLA', '63.698908', '9.604003')
('RRS', '62.578411', '11.342347')
('RYG', '59.378933', '10.785389')
('LYR', '78.246111', '15.465556')
('SKE', '59.185', '9.566944')
('SRP', '59.791925', '5.34085')
('SSJ', '65.956828', '12.468944')
('TOS', '69.683333', '18.918919')
('TRF', '59.186703', '10.258628')
('TRD', '63.457556', '10.92425')
('SVG', '58.876778', '5.637856')
('GDN', '54.377569', '18.466222')
('KRK', '50.077731', '19.784836')
('KTW', '50.474253', '19.080019')
('POZ', '52.421031', '16.826325')
('RZE', '50.109958', '22.019')
('SZZ', '53.584731', '14.902206')
('WAW', '52.16575', '20.967122')
('WRO', '51.102683', '16.885836')
('RNB', '56.266667', '15.265')
('GOT', '57.662836', '12.279819')
('JKG', '57.757594', '14.068731')
('GSE', '57.774722', '11.870372')
('THN', '58.318056', '12.345')
('MXX', '60.957908', '14.511383')
('NYO', '58.788636', '16.912189')
('KID', '55.921686', '14.085536')
('KLR', '56.685531', '16.287578')
('MMX', '55.530193', '13.371639')
('HAD', '56.691128', '12.820211')
('VXO', '56.929144', '14.727994')
('EVG', '62.047811', '14.42295')
('GEV', '67.132408', '20.814636')
('KRF', '63.048597', '17.768856')
('LYC', '64.548322', '18.716219')
('SDL', '62.528125', '17.443928')
('OER', '63.408339', '18.990039')
('KRN', '67.821986', '20.336764')
('SFT', '64.624772', '21.076892')
('UME', '63.791828', '20.282758')
('VHM', '64.579083', '16.833575')
('AJR', '65.590278', '19.281944')
('ORB', '59.223733', '15.037956')
('VST', '59.589444', '16.633611')
('LLA', '65.543758', '22.121989')
('ARN', '59.651944', '17.918611')
('BMA', '59.354372', '17.94165')
('BLE', '60.422017', '15.515211')
('LPI', '58.40615', '15.680508')
('NRK', '58.586253', '16.250622')
('VBY', '57.662797', '18.346211')
('RLG', '53.918167', '12.278333')
('BFN', '-29.092722', '26.302444')
('CPT', '-33.964806', '18.601667')
('DUR', '-29.970089', '30.950519')
('ELS', '-33.035569', '27.825939')
('GRJ', '-34.005553', '22.378889')
('HDS', '-24.368642', '31.048744')
('JNB', '-26.139166', '28.246')
('KIM', '-28.802834', '24.765167')
('HLA', '-25.938514', '27.926133')
('MGH', '-30.857408', '30.343019')
('PLZ', '-33.984919', '25.617275')
('PHW', '-23.937166', '31.15539')
('PTG', '-23.926089', '29.484422')
('PZB', '-29.648975', '30.398667')
('RCB', '-28.741039', '32.092111')
('UTN', '-28.399097', '21.260239')
('UTT', '-31.547903', '28.674289')
('FRW', '-21.159597', '27.474525')
('BBK', '-17.832875', '25.1624')
('MUB', '-19.972564', '23.431086')
('GBE', '-24.555225', '25.918208')
('BZV', '-4.2517', '15.253031')
('PNR', '-4.816028', '11.886597')
('MTS', '-26.529022', '31.307519')
('BGF', '4.398475', '18.518786')
('BSG', '1.905469', '9.805681')
('SSG', '3.755267', '8.708717')
('MRU', '-20.430235', '57.6836')
('RRG', '-19.757658', '63.360983')
('DLA', '4.006081', '9.719481')
('MVR', '10.451392', '14.257361')
('NGE', '7.357011', '13.559242')
('GOU', '9.335892', '13.370103')
('LVI', '-17.821756', '25.822692')
('LUN', '-15.330817', '28.452628')
('MFU', '-13.258878', '31.936581')
('NLA', '-12.998139', '28.664944')
('HAH', '-11.533661', '43.27185')
('DZA', '-12.804722', '45.281113')
('RUN', '-20.8871', '55.510308')
('ZSE', '-21.320039', '55.423581')
('TNR', '-18.79695', '47.478806')
('SMS', '-17.093889', '49.815834')
('TMM', '-18.109517', '49.392536')
('MOQ', '-20.28475', '44.317614')
('DIE', '-12.3494', '49.291747')
('WMR', '-16.1639', '49.773753')
('ANM', '-14.999411', '50.320233')
('MJN', '-15.667144', '46.351828')
('NOS', '-13.312067', '48.314822')
('WMN', '-15.436666', '49.688332')
('SVB', '-14.278611', '50.174721')
('FTU', '-25.038056', '46.956111')
('TLE', '-23.383369', '43.728453')
('SSY', '-6.269897', '14.247025')
('CAB', '-5.596992', '12.188353')
('CPX', '18.3127', '-65.3034')
('NOV', '-12.808878', '15.760547')
('SVP', '-12.404633', '16.947414')
('LAD', '-8.858375', '13.231178')
('MEG', '-9.525086', '16.312406')
('SPP', '-14.657583', '17.719833')
('VHC', '-9.689067', '20.431875')
('SZA', '-6.141086', '12.371764')
('SDD', '-14.924733', '13.575022')
('LUO', '-11.768086', '19.897672')
('POG', '-0.711739', '8.754383')
('LBV', '0.4586', '9.412283')
('TMS', '0.378175', '6.712153')
('BEW', '-19.796419', '34.907556')
('INH', '-23.876431', '35.408544')
('VXC', '-13.273986', '35.266262')
('MPM', '-25.920836', '32.572606')
('APL', '-15.105611', '39.2818')
('POL', '-12.986753', '40.522492')
('UEL', '-17.8555', '36.869106')
('TET', '-16.104817', '33.640181')
('VNX', '-22.018431', '35.313297')
('SEZ', '-4.674342', '55.521839')
('PRI', '-4.319292', '55.691417')
('NDJ', '12.133689', '15.034019')
('BUQ', '-20.017431', '28.617869')
('VFA', '-18.095881', '25.839006')
('HRE', '-17.931806', '31.092847')
('BLZ', '-15.679053', '34.974014')
('LLW', '-13.789378', '33.781')
('MSU', '-29.462256', '27.552503')
('FIH', '-4.38575', '15.444569')
('MDK', '0.0226', '18.288744')
('GMA', '3.235369', '19.771258')
('FKI', '0.5175', '25.155014')
('IRP', '2.827606', '27.588253')
('BUX', '1.565719', '30.220833')
('BKY', '-2.308978', '28.808803')
('GOM', '-1.670814', '29.238464')
('KND', '-2.919178', '25.915361')
('FBM', '-11.591333', '27.530889')
('KGA', '-5.900055', '22.469166')
('MJM', '-6.121236', '23.569008')
('BKO', '12.533544', '-7.949944')
('BJL', '13.337961', '-16.652206')
('FUE', '28.452717', '-13.863761')
('VDE', '27.814847', '-17.887056')
('SPC', '28.626478', '-17.755611')
('LPA', '27.931886', '-15.386586')
('ACE', '28.945464', '-13.605225')
('TFS', '28.044475', '-16.572489')
('TFN', '28.482653', '-16.341536')
('MLN', '35.279817', '-2.956256')
('FNA', '8.616444', '-13.195489')
('MLW', '6.289061', '-10.758722')
('ROB', '6.233789', '-10.362311')
('AGA', '30.381353', '-9.546311')
('TTA', '28.448194', '-11.161347')
('FEZ', '33.927261', '-4.977958')
('OUD', '34.78715', '-1.923986')
('RBA', '34.051467', '-6.751519')
('CMN', '33.367467', '-7.589967')
('RAK', '31.606886', '-8.0363')
('OZZ', '30.939053', '-6.909431')
('AHU', '35.177103', '-3.839525')
('TTU', '35.594333', '-5.320019')
('TNG', '35.726917', '-5.916889')
('ZIG', '12.555617', '-16.281783')
('CSK', '12.4102', '-16.746125')
('DKR', '14.739708', '-17.490225')
('NKC', '18.097856', '-15.947956')
('NDB', '20.933067', '-17.029956')
('SID', '16.741389', '-22.949444')
('BVC', '16.136531', '-22.888897')
('MMO', '15.155928', '-23.213703')
('SNE', '16.588356', '-24.284656')
('VXE', '16.833689', '-25.054661')
('ADD', '8.977889', '38.799319')
('AMH', '6.039389', '37.590453')
('AXU', '14.14675', '38.772833')
('BJR', '11.608075', '37.321644')
('DIR', '9.6247', '41.854203')
('GMB', '8.128764', '34.563131')
('GDQ', '12.5199', '37.434047')
('JIM', '7.666094', '36.816639')
('LLI', '11.975014', '38.979969')
('MQX', '13.467367', '39.533464')
('ASO', '10.01855', '34.586253')
('BJM', '-3.324019', '29.318519')
('HGA', '9.518167', '44.088758')
('BBO', '10.389167', '44.941106')
('ABS', '22.375953', '31.611722')
('CAI', '30.121944', '31.405556')
('HRG', '27.178317', '33.799436')
('LXR', '25.671028', '32.706583')
('ASW', '23.964356', '32.819975')
('EDL', '0.404458', '35.238928')
('KIS', '-0.086139', '34.728892')
('KTL', '0.971989', '34.958556')
('LOK', '3.121967', '35.608692')
('LAU', '-2.252417', '40.913097')
('MBA', '-4.034833', '39.59425')
('WIL', '-1.321719', '36.814833')
('WJR', '1.733239', '40.091606')
('GHT', '25.145564', '10.142647')
('AKF', '24.178728', '23.313958')
('BEN', '32.096786', '20.269472')
('TIP', '32.663544', '13.159011')
('LTD', '30.151695', '9.715305')
('KGL', '-1.968628', '30.13945')
('KME', '-2.462242', '28.90795')
('ELF', '13.614892', '25.32465')
('JUB', '4.872006', '31.601117')
('KRT', '15.589497', '32.553161')
('ARK', '-3.367794', '36.633333')
('DAR', '-6.878111', '39.202625')
('JRO', '-3.429406', '37.074461')
('MYW', '-10.339058', '40.181781')
('MWZ', '-2.444486', '32.932667')
('ZNZ', '-6.222025', '39.224886')
('EBB', '0.042386', '32.443503')
('TIA', '41.414742', '19.720561')
('BOJ', '42.569583', '27.515236')
('PDV', '42.067806', '24.850833')
('SOF', '42.695194', '23.406167')
('VAR', '43.232072', '27.825106')
('LCA', '34.875117', '33.62485')
('PFO', '34.718039', '32.485731')
('DBV', '42.561353', '18.268244')
('OSI', '45.462667', '18.810156')
('PUY', '44.893533', '13.922192')
('RJK', '45.216889', '14.570267')
('SPU', '43.538944', '16.297964')
('ZAG', '45.742931', '16.068778')
('ZAD', '44.108269', '15.346697')
('ALC', '38.282169', '-0.558156')
('LEI', '36.843936', '-2.370097')
('OVD', '43.563567', '-6.034622')
('BIO', '43.301097', '-2.910608')
('BCN', '41.297078', '2.078464')
('BJZ', '38.89125', '-6.821333')
('LCG', '43.302061', '-8.377256')
('GRO', '41.900969', '2.760547')
('GRX', '37.188731', '-3.777356')
('IBZ', '38.872858', '1.373117')
('XRY', '36.744622', '-6.060111')
('MJV', '37.774972', '-0.812389')
('MAD', '40.493556', '-3.566764')
('AGP', '36.6749', '-4.499106')
('MAH', '39.862597', '4.218647')
('PNA', '42.770039', '-1.646331')
('REU', '41.147392', '1.167172')
('SLM', '40.952117', '-5.501986')
('EAS', '43.356519', '-1.790611')
('SCQ', '42.896333', '-8.415144')
('VLC', '39.489314', '-0.481625')
('VLL', '41.706111', '-4.851944')
('VGO', '42.2318', '-8.626775')
('SDR', '43.427064', '-3.820006')
('ZAZ', '41.666242', '-1.041553')

('MDT', '40.193494', '-76.763403')
('LNK', '40.850971', '-96.75925')
('LAN', '42.7787', '-84.587357')
('MUE', '20.001328', '-155.668108')
('MSS', '44.935833', '-74.845547')
('IAH', '29.984433', '-95.341442')
('BFL', '35.433598', '-119.05677')
('ELP', '31.80725', '-106.377583')
('HRL', '26.2285', '-97.654389')
('CAE', '33.938833', '-81.119528')
('PNS', '30.473425', '-87.186611')
('HOU', '29.645419', '-95.278889')
('PIT', '40.491467', '-80.232872')
('BRW', '71.285446', '-156.766003')
('MIA', '25.79325', '-80.290556')
('SEA', '47.449', '-122.309306')
('CHA', '35.035278', '-85.203808')
('JAN', '32.311167', '-90.075889')
('LGB', '33.817722', '-118.151611')
('IPT', '41.241836', '-76.921094')
('IND', '39.717331', '-86.294383')
('HPN', '41.066959', '-73.707575')
('JBR', '35.831708', '-90.646417')
('YUM', '32.656578', '-114.60598')
('CNM', '32.337472', '-104.263278')
('DLH', '46.842091', '-92.193649')
('BET', '60.779778', '-161.838')
('LIH', '21.975983', '-159.338958')
('HVR', '48.542983', '-109.762342')
('RIC', '37.505167', '-77.319667')
('SHV', '32.446629', '-93.8256')
('CDV', '60.491778', '-145.477556')
('ORF', '36.894611', '-76.201222')
('BPT', '29.950833', '-94.020694')
('SAV', '32.127583', '-81.202139')
('OME', '64.512203', '-165.445247')
('SPB', '45.771028', '-122.861833')
('PIE', '27.910167', '-82.687389')
('SCC', '70.19475', '-148.465167')
('SAT', '29.533694', '-98.469778')
('ROC', '43.118866', '-77.672389')
('TEB', '40.850103', '-74.060837')
('RDU', '35.877639', '-78.787472')
('DAY', '39.902375', '-84.219375')
('ENA', '60.573111', '-151.245')
('IAG', '43.107333', '-78.946194')
('PHF', '37.131894', '-76.492989')
('TUS', '32.116083', '-110.941028')
('PVD', '41.732581', '-71.420383')
('SBY', '38.340525', '-75.510289')
('BUR', '34.200667', '-118.358667')
('DTW', '42.212444', '-83.353389')
('TPA', '27.975472', '-82.53325')
('HIB', '47.3866', '-92.838994')
('MAF', '31.942528', '-102.201914')
('GRB', '44.485072', '-88.129589')
('AGS', '33.369944', '-81.9645')
('ISN', '48.177939', '-103.642347')
('LIT', '34.729444', '-92.224306')
('SWF', '41.504094', '-74.104839')
('HOM', '59.645556', '-151.476583')
('TBN', '37.741631', '-92.140736')
('DFW', '32.896828', '-97.037997')
('MLB', '28.102753', '-80.645258')
('AUS', '30.194528', '-97.669889')
('LCK', '39.813786', '-82.927822')
('TYS', '35.810972', '-83.994028')
('STL', '38.748697', '-90.370028')
('SPS', '33.988797', '-98.491894')
('LUK', '39.103333', '-84.418611')
('ATL', '33.636719', '-84.428067')
('GRR', '42.880833', '-85.522806')
('FAT', '36.776194', '-119.71814')
('IPL', '32.834219', '-115.578744')
('BNA', '36.124472', '-86.678194')
('LRD', '27.54375', '-99.461556')
('OTZ', '66.884678', '-162.59855')
('AOO', '40.296372', '-78.320022')
('ELD', '33.220972', '-92.813278')
('LGA', '40.777245', '-73.872608')
('TLH', '30.396528', '-84.350333')
('ACT', '31.611289', '-97.230519')
('AUG', '44.320647', '-69.797317')
('MKL', '35.599889', '-88.915611')
('MKK', '21.152886', '-157.096256')
('SJT', '31.35775', '-100.496306')
('CIC', '39.795383', '-121.858422')
('BTV', '44.471861', '-73.153278')
('JAX', '30.494056', '-81.687861')
('DRO', '37.151516', '-107.75377')
('IAD', '38.944533', '-77.455811')
('CLL', '30.588583', '-96.363833')
('MKE', '42.947222', '-87.896583')
('ABI', '32.411319', '-99.681897')
('COU', '38.818094', '-92.219631')
('PDX', '45.588722', '-122.5975')
('PBI', '26.683161', '-80.095589')
('OGS', '44.681854', '-75.4655')
('BFI', '47.53', '-122.301947')
('HNL', '21.318681', '-157.922428')
('DSM', '41.533972', '-93.663083')
('EWN', '35.072972', '-77.042944')
('SAN', '32.733556', '-117.189667')
('MLU', '32.510864', '-92.037689')
('ONT', '34.056', '-117.601194')
('ROW', '33.301556', '-104.530556')
('BRO', '25.906833', '-97.425861')
('DHN', '31.321339', '-85.449628')
('FMN', '36.74125', '-108.229944')
('CRP', '27.770361', '-97.501222')
('SYR', '43.111187', '-76.106311')
('MDW', '41.785972', '-87.752417')
('SJC', '37.3626', '-121.929022')
('HOB', '32.687528', '-103.217028')
('DEN', '39.861656', '-104.673178')
('PHL', '39.871944', '-75.241139')
('SUX', '42.402603', '-96.384367')
('MCN', '32.69285', '-83.649211')
('CMH', '39.997972', '-82.891889')
('GAL', '64.736178', '-156.937417')
('TXK', '33.453722', '-93.991028')
('PBG', '44.650944', '-73.468139')
('ANC', '61.174361', '-149.996361')
('GRK', '31.06725', '-97.828917')
('BLI', '48.792694', '-122.537528')
('MOB', '30.691231', '-88.242814')
('SAF', '35.617108', '-106.089422')
('BLV', '38.545178', '-89.835183')
('RSW', '26.536167', '-81.755167')
('AKN', '58.676778', '-156.649278')
('JHM', '20.962936', '-156.673031')
('JFK', '40.639751', '-73.778925')
('CYS', '41.155722', '-104.811839')
('SCK', '37.894167', '-121.238306')
('CHS', '32.898647', '-80.040528')
('RNO', '39.499108', '-119.768108')
('KTN', '55.355556', '-131.71375')
('BHM', '33.562942', '-86.75355')
('MOD', '37.625817', '-120.954422')
('SMF', '38.695417', '-121.590778')
('COS', '38.805805', '-104.700778')
('BUF', '42.940525', '-78.732167')
('CDC', '37.700967', '-113.098847')
('BDL', '41.938889', '-72.683222')
('MFE', '26.175833', '-98.238611')
('LBB', '33.663639', '-101.822778')
('ORD', '41.978603', '-87.904842')
('FAI', '64.815114', '-147.856267')
('ART', '43.991922', '-76.021739')
('PSP', '33.829667', '-116.506694')
('AMA', '35.219369', '-101.705931')
('FOE', '38.950944', '-95.663611')
('ILM', '34.270615', '-77.902569')
('BTR', '30.533167', '-91.149639')
('TYR', '32.354139', '-95.402386')
('BWI', '39.175361', '-76.668333')
('LNY', '20.785611', '-156.951419')
('AEX', '31.3274', '-92.549833')
('CDB', '55.206061', '-162.725436')
('TUL', '36.198389', '-95.888111')
('SIT', '57.047138', '-135.361611')
('ISP', '40.79525', '-73.100222')
('MSP', '44.881956', '-93.221767')
('ILG', '39.678722', '-75.606528')
('DUT', '53.900139', '-166.5435')
('MSY', '29.993389', '-90.258028')
('PWM', '43.646161', '-70.309281')
('OKC', '35.393089', '-97.600733')
('ALB', '42.748267', '-73.801692')
('VDZ', '61.133949', '-146.248342')
('SNA', '33.675667', '-117.868222')
('CPR', '42.908', '-106.464417')
('VPS', '30.48325', '-86.5254')
('EYW', '24.556111', '-81.759556')
('CLT', '35.214', '-80.943139')
('LAS', '36.080056', '-115.15225')
('MCO', '28.429394', '-81.308994')
('FLO', '34.185361', '-79.723889')
('GTF', '47.482', '-111.370689')
('YNG', '41.260736', '-80.679097')
('BKK', '13.681108', '100.747283')
('KDI', '-4.081608', '122.418231')
('MLG', '-7.926556', '112.714514')
('BDO', '-6.900625', '107.576294')
('JOG', '-7.788181', '110.431758')
('SRG', '-6.971447', '110.374122')
('BTH', '1.121028', '104.118753')
('TJQ', '-2.745722', '107.754917')
('PGK', '-2.1622', '106.139064')
('TNJ', '0.922683', '104.532311')
('BDJ', '-3.442356', '114.762553')
('PKN', '-2.705197', '111.673208')
('PKY', '-2.225128', '113.942661')
('MOF', '-8.640647', '122.236889')
('ENE', '-8.849294', '121.660644')
('KOE', '-10.171583', '123.671136')
('LBJ', '-8.486656', '119.88905')
('BPN', '-1.268272', '116.894478')
('TRK', '3.326694', '117.565569')
('BMU', '-8.539647', '118.687322')
('WGP', '-9.669217', '120.302006')
('SUB', '-7.379831', '112.786858')
('SOC', '-7.516089', '110.756892')
('CNX', '18.766847', '98.962644')
('CEI', '19.952342', '99.882928')
('NST', '8.539617', '99.944725')
('DPS', '-8.748169', '115.167172')
('KOP', '17.383794', '104.643022')
('UBP', '15.251278', '104.870231')
('KKC', '16.466628', '102.783661')
('THS', '17.237992', '99.818183')
('ATH', '37.936358', '23.944467')
('NGO', '34.858414', '136.805408')
('UKB', '34.632778', '135.223889')
('PUW', '46.743861', '-117.109583')
('LWS', '46.3745', '-117.015389')
('ELM', '42.159889', '-76.891611')
('ITH', '42.491028', '-76.458444')
('MRY', '36.587', '-121.842944')
('SBA', '34.426211', '-119.840372')
('DAB', '29.179917', '-81.058056')
('RIX', '56.923611', '23.971111')
('KUN', '54.963919', '24.084778')
('PLQ', '55.973228', '21.093856')
('VNO', '54.634133', '25.285767')
('EVN', '40.147275', '44.395881')
('LWN', '40.750369', '43.859342')
('ASM', '15.291853', '38.910667')
('MSW', '15.669989', '39.370103')
('RIY', '14.662639', '49.375028')
('BUS', '41.610278', '41.599694')
('KUT', '42.176653', '42.482583')
('TBS', '41.669167', '44.954722')
('TAI', '13.685964', '44.139056')
('HOD', '14.753', '42.976336')
('ADE', '12.829542', '45.028792')
('AXK', '14.551322', '46.826183')
('AAY', '16.191667', '52.175')
('SAH', '15.476258', '44.219739')
('FMM', '47.988758', '10.2395')
('SCT', '12.630672', '53.905778')
('NAV', '38.771867', '34.53455')
('EZE', '-34.822222', '-58.535833')
('EBL', '36.237611', '43.963158')
('EMD', '-23.5675', '148.179167')
('KIX', '34.4347222', '135.244167')
('TAG', '9.66408056', '123.853247')
('JAV', '69.23444', '-51.05111')
('JEG', '68.7', '-52.75')
('PMI', '39.55361', '2.727778')
('DRW', '-12.4083333', '130.87266')
('URT', '9.1325', '99.135556')
('NYU', '21.173833266', '94.9246666')
('MPH', '11.9214999', '121.953')
('HVN', '41.26375', '-72.886806')
('AVL', '35.436194', '-82.541806')
('GSO', '36.09775', '-79.937306')
('FSD', '43.582014', '-96.741914')
('AYQ', '-25.186111', '130.975556')
('MHT', '42.932556', '-71.435667')
('APF', '26.152619', '-81.775294')
('RDN', '5.76528', '103.007')
('SDF', '38.1740858', '-85.7364989')
('CHO', '38.138639', '-78.452861')
('ROA', '37.325472', '-79.975417')
('LEX', '38.0365', '-84.605889')
('EVV', '38.036997', '-87.532364')
('ABQ', '35.0402222', '-106.6091944')
('BZN', '45.777643', '-111.160151')
('BIL', '45.80921', '-108.537654')
('BTM', '45.954806', '-112.497472')
('TVC', '44.741445', '-85.582235')
('FRS', '16.913819', '-89.866383')
('BHB', '44.4497689', '-68.3615653')
('RKD', '44.0601111', '-69.0992303')
('JAC', '43.607333333', '-110.73775')
('RFD', '42.1953611', '-89.0972222')
('DME', '55.408611', '37.906111')
('SYX', '18.302897', '109.412272')
('LJG', '26.883333', '100.23333')
('GSP', '34.895556', '-82.218889')
('BMI', '40.477111', '-88.915917')
('GPT', '30.407278', '-89.070111')
('AZO', '42.234875', '-85.552058')
('TOL', '41.586806', '-83.807833')
('FWA', '40.978472', '-85.195139')
('DEC', '39.834564', '-88.865689')
('CID', '41.884694', '-91.710806')
('LSE', '43.878986', '-91.256711')
('CWA', '44.772726', '-89.646635')
('PIA', '40.664203', '-89.693258')
('ATW', '44.257526', '-88.507576')
('RST', '43.908283', '-92.500014')
('CMI', '40.03925', '-88.278056')
('MHK', '39.140972', '-96.670833')
('KGC', '-35.713889', '137.521389')
('HVB', '-25.318889', '152.880278')
('BSL', '47.59', '7.529167')
('DLU', '25.649444', '100.319444')
('JHG', '21.973914', '100.759611')
('MZV', '4.048333', '114.805')
('SSH', '27.977222', '34.394722')
('FKL', '41.377874', '-79.860362')
('NBO', '-1.319167', '36.9275')
('FTE', '-50.280322', '-72.053103')
('ARM', '-30.528056', '151.617222')
('GJT', '39.122413', '-108.526735')
('SGU', '37.090583', '-113.593056')
('SRQ', '27.395444', '-82.554389')
('BDA', '32.364042', '-64.678703')
('MLI', '41.448528', '-90.507539')
('HIR', '-9.428', '160.054789')
('PPT', '-17.556667', '-149.611389')
('INU', '-0.547458', '166.9191')
('FUN', '-8.525', '179.196389')
('OVB', '55.012622', '82.650656')
('XKH', '19.449997', '103.158333')
('HUI', '16.401499', '107.702614')
('BIS', '46.775842', '-100.757931')
('INC', '38.481944', '106.009167')
('HGN', '19.301667', '97.975')
('RAP', '44.045278', '-103.057222')
('CLD', '33.0742', '-117.1648')
('FNT', '42.965424', '-83.743629')
('DVO', '7.125522', '125.645778')
('FNC', '32.697889', '-16.774453')
('STM', '-2.422431', '-54.792789')
('KOS', '10.579686', '103.636828')
('NPE', '-39.465833', '176.87')
('LXA', '29.297778', '90.911944')
('RDD', '40.509', '-122.293389')
('EUG', '44.124583', '-123.211972')
('IDA', '43.514556', '-112.07075')
('MFR', '42.374228', '-122.8735')
('RDM', '44.254066', '-121.149964')
('WDH', '-22.486667', '17.4625')
('YWH', '48.422778', '-123.3875')
('CXH', '49.289722', '-123.115833')
('TNA', '36.857214', '117.215992')
('CZX', '31.941667', '119.711667')
('YBP', '28.800278', '104.544444')
('TJM', '57.189567', '65.3243')
('CAK', '40.9160833', '-81.4421944')
('HSV', '34.6371944', '-86.7750556')
('PKB', '39.3451039', '-81.4392031')
('MGM', '32.3006389', '-86.3939722')
('TRI', '36.4752222', '-82.4074167')
('PAH', '37.0602875', '-88.7729583')
('KUF', '53.5', '50.15')
('JIB', '11.5472', '43.1594')
('HAK', '19.934856', '110.458961')
('FCA', '48.310472', '-114.256')
('PGA', '36.9261', '-111.4483')
('SNV', '4.554722', '-61.144922')
('MBS', '43.532913', '-84.079647')
('BGM', '42.208689', '-75.979839')
('BGW', '33.262539', '44.234578')
('NNT', '18.807914', '100.783419')
('ROI', '16.116761', '103.773797')
('BFV', '15.229539', '103.253231')
('UNN', '9.777622', '98.585483')
('TDX', '12.274572', '102.318958')
('CRK', '15.185833', '120.560278')
('SDK', '5.900897', '118.059486')
('LXG', '20.960556', '101.4025')
('ODY', '20.6827', '101.994')
('SHE', '41.3824', '123.2901')
('DOY', '37.2716', '118.2819')
('PSG', '56.801667', '-132.945278')
('LYA', '34.41', '112.28')
('XUZ', '34.16', '117.11')
('IFN', '32.750836', '51.861267')
('DLI', '11.75', '108.367')
('VDH', '17.515', '106.590556')
('VKG', '9.949676', '105.133659')
('CAH', '9.188049', '105.174721')
('VCL', '15.405944', '108.705889')
('TBB', '13.04955', '109.333706')
('PYY', '19.372', '98.437')
('BWK', '43.285719', '16.679719')
('NSI', '3.722556', '11.553269')
('CKY', '9.576889', '-13.611961')
('FKB', '48.7793', '8.08048')
('SFB', '28.777639', '-81.237489')
('PQC', '10.227025', '103.967169')
('JST', '40.316111', '-78.833889')
('TMI', '27.315', '87.193333')
('DHI', '28.753333', '80.581944')
('MWX', '34.991389', '126.382778')
('JTY', '36.579886', '26.375822')
('JIK', '37.682717', '26.347061')
('JKL', '36.963333', '26.940556')
('MLO', '36.696111', '24.4775')
('JNX', '37.080556', '25.368056')
('PAS', '37.010278', '25.127778')
('KZS', '36.127777', '29.566656')
('RMF', '25.557111', '34.583711')
('NRN', '51.602222', '6.141944')
('USU', '12.121458', '120.100031')
('BXU', '8.951322', '125.477972')
('DPL', '8.601261', '123.334481')
('LAO', '18.178092', '120.531522')
('LGP', '13.157064', '123.746247')
('OZC', '8.178508', '123.841731')
('ZQW', '49.209445', '7.401323')
('CEB', '10.307542', '123.979439')
('BPS', '-16.438611', '-39.080833')
('PMW', '-10.241667', '-48.35278')
('CLV', '-17.7267', '-48.6114')
('MSO', '46.916306', '-114.090556')
('BKQ', '-24.427778', '145.428611')
('BDB', '-24.903889', '152.318611')
('GCN', '35.9523611', '-112.1469722')
('KDM', '0.4880555', '72.995556')
('YWJ', '65.1833333', '-125.41666667')
('ZFN', '64.0833333', '-125.5833333')
('YGH', '66.26666667', '-128.65')
('TAH', '-19.455198', '169.22394')
('YPC', '62.35', '-124.3333')
('SRZ', '-17.8', '-63.166667')
('KUS', '65.566667', '-37.1166667')
('SAB', '17.645278', '-63.220556')
('EGE', '39.642556', '-106.917694')
('SKN', '68.580833', '15.026111')
('CSG', '32.5163333', '-84.9388611')
('LAW', '34.5677144', '-98.4166367')
('FLG', '35.140318', '-111.6692392')
('TWF', '42.481803', '-114.487733')
('MCM', '43.73333333', '7.41666666')
('MVY', '41.391667', '-70.615278')
('STC', '45.546556', '-94.059889')
('GTR', '33.450333', '-88.591361')
('GOJ', '56.230119', '43.784042')
('ERI', '42.082022', '-80.176217')
('HYA', '41.669336', '-70.280356')
('SPR', '17.913936', '-87.971075')
('MGW', '39.642908', '-79.916314')
('CRW', '38.373147', '-81.593189')
('AVP', '41.338478', '-75.723403')
('BJI', '47.510722', '-94.934722')
('BNK', '-28.833889', '153.5625')
('FAR', '46.92065', '-96.8157639')
('AZA', '33.307833', '-111.655')
('GCC', '44.3489167', '-105.5393611')
('TOF', '56.380278', '85.208333')
('CJM', '10.7112', '99.361706')
('JZH', '32.857', '103.683')
('SWA', '23.4', '116.683')
('GEO', '6.498553', '-58.254119')
('AGT', '-25.4555', '-54.843592')
('OGL', '6.806944', '-58.104444')
('DNH', '40.094', '94.4818')
('AOI', '43.616389', '13.362222')
('CPO', '-27', '-70')
('LYB', '19.6591666667', '-80.09083333')
('BJV', '37.249', '27.667')
('SAW', '40.898553', '29.309219')
('SCE', '40.849278', '-77.848694')
('BME', '-17.8', '122.2')
('NTL', '-32.78', '151.83')
('KLU', '46.642514', '14.337739')
('HFT', '70.679722', '23.668889')
('HVG', '70.99', '25.83')
('MEH', '71.029722', '27.826667')
('VDS', '70.065', '29.844')
('IKA', '35.416111', '51.152222')
('MHD', '36.234', '59.643')
('MDG', '44.523889', '129.568889')
('MEI', '32.332624', '-88.751868')
('CEZ', '37.303', '-108.628056')
('HDN', '40.481181', '-107.21766')
('LBL', '37.044222', '-100.95986')
('COD', '44.520194', '-109.023806')
('HOV', '62.18', '6.0742')
('ISC', '49.919', '-6.3075')
('SGF', '37.245667', '-93.388639')
('NVK', '68.435833', '17.388056')
('BVG', '70.866667', '29')
('NSK', '69.311053', '87.332183')
('AAQ', '45.002097', '37.347272')
('JLN', '37.151814', '-94.498269')
('ABE', '40.652083', '-75.440806')
('XNA', '36.2818694', '-94.3068111')
('GUW', '47.121944', '51.821389')
('KZO', '44.709', '65.591')
('SBN', '41.708661', '-86.31725')
('ARH', '64.360281', '40.430167')
('RTW', '51.334366', '46.022952')
('NUX', '66.041811', '76.313938')
('NOJ', '63.110079', '75.162243')
('SCO', '43.86005', '51.091978')
('UCT', '63.340297', '53.482592')
('USK', '66.00077', '57.221113')
('NNM', '67.380537', '53.051016')
('KGP', '62.18', '74.53')
('KJA', '56.18', '92.475')
('KGF', '49.670833', '73.334444')
('URJ', '60.1', '64.83')
('CGQ', '43.5412', '125.1201')
('KIJ', '37.5711', '139.0646')
('ACV', '40.978111', '-124.108611')
('ATT', '30.31666', '-97.7666')
('OAJ', '34.829164', '-77.612139')
('DBQ', '42.402', '-90.709472')
('FDE', '61.392', '5.763')
('PYJ', '66.400431', '112.030325')
('NAJ', '39.1888', '45.4584')
('KVD', '40.7377', '46.3176')
('UKK', '50.0366', '82.4942')
('PPK', '54.7747', '69.1839')
('JPR', '-10.8708', '-61.8465')
('CJA', '-7.139183', '-78.4894')
('EYP', '5.319114', '-72.383975')
('ESM', '0.978519', '-79.6266')
('RIA', '-29.711358', '-53.688153')
('LEC', '-12.4823', '-41.277')
('JDO', '-7.218958', '-39.2701')
('MBT', '12.3694', '123.629')
('CRM', '12.502417', '124.635778')
('JOL', '6.05367', '121.011')
('CGM', '9.25352', '124.707')
('CJJ', '36.7166', '127.499119')
('HIN', '35.088543', '128.07037')
('WJU', '37.438081', '127.960383')
('KUV', '35.903756', '126.615906')
('SYO', '38.812222', '139.787222')
('ONJ', '40.1919', '140.371')
('FKS', '37.2274', '140.431')
('IWJ', '34.6764', '131.79')
('NKM', '35.255', '136.924')
('HSG', '33.1497', '130.302')
('KUH', '43.041', '144.193')
('TFI', '-9.07595', '149.32')
('LSA', '-8.50582', '151.081')
('LNV', '-3.04361', '152.629')
('WRG', '56.4843', '-132.37')
('VAK', '61.5338', '-165.584')
('ANI', '61.5816', '-159.543')
('MOU', '62.0954', '-163.682')
('MCG', '62.9529', '-155.606')
('KLG', '61.5363', '-160.341')
('HNS', '59.2438', '-135.524')
('HCR', '62.1883', '-159.775')
('SGY', '59.4601', '-135.316')
('GST', '58.4253', '-135.707')
('ADK', '51.878', '-176.646')
('SAX', '8.017', '-78.2')
('OTD', '8.62876', '-79.0347')
('BFQ', '7.583', '-78.2')
('GXF', '15.966111', '48.7883')
('ISU', '35.5608', '45.3147')
('TUK', '25.986369', '63.030167')
('KDU', '35.335508', '75.536047')
('DSK', '31.909422', '70.896639')
('DEA', '29.961011', '70.485925')
('DBA', '28.8783', '64.3998')
('CJL', '35.886592', '71.800578')
('BHV', '29.3481', '71.717981')
('AAN', '24.261667', '55.609167')
('OMH', '37.6681', '45.0687')
('ADU', '38.325678', '48.424356')
('LRR', '27.674725', '54.383278')
('SRY', '36.635833', '53.193611')
('NSH', '36.663333', '51.464722')
('AFZ', '36.168083', '57.595183')
('BJB', '37.492958', '57.308219')
('BXR', '29.084169', '58.450042')
('KHD', '33.435378', '48.282889')
('AJF', '29.785133', '40.100006')
('DWD', '24.5', '44.4')
('ILP', '-22.5889', '167.456')
('BMY', '-19.7206', '163.661')
('TGJ', '-21.0961', '167.804')
('IPA', '-18.8783', '169.308')
('FTA', '-19.5164', '170.232')
('DLY', '-18.7694', '169.001')
('AWD', '-19.24', '169.605')
('AUY', '-20.2492', '169.771')
('SWJ', '-16.495', '167.438')
('VLS', '-16.7961', '168.177')
('ULB', '-16.333', '168.283')
('TGH', '-16.8911', '168.551')
('SON', '-15.505033', '167.219742')
('ZGU', '-14.2181', '167.587')
('NUS', '-16.0797', '167.401')
('LNE', '-15.8656', '168.172')
('MWF', '-15', '168.083')
('LNB', '-16.5842', '168.159')
('LPM', '-16.454', '167.823')

('UMD', '70.4047', '52.0702')
('RLK', '40.926389', '107.738889')
('PUM', '-4.183333', '121.61667')
('RGK', '51.966667', '85.833333')
('LLK', '38.746389', '48.817778')
('GBB', '40.826667', '47.7125')
('JIQ', '29.515', '108.83')
('DEE', '43.5739', '145.4107')
('NBS', '42.088056', '127.548889')
('LUZ', '51.239333', '22.714083')
('LLF', '26.345556', '111.612222')
('TVS', '39.717444', '118.002389')
('YTY', '32.5617', '119.715')
('GKK', '0.7308', '73.433')
('RHD', '-27.509946', '-64.936666')
('KGT', '30.1575', '101.734722')
('VUS', '60.788333', '46.26')
('ODO', '57.5137', '114.1348')
('HRI', '6.284467', '81.124128')
('XSB', '24.2856083', '52.5783472')
('ZDY', '24.5033833', '52.3360528')
('JGD', '50.375', '124.117')
('BFJ', '27.253', '105.426')
('ULK', '60.723', '114.825')
('IGD', '39.983056', '43.866389')
('GNY', '37.45', '38.9')
('KZR', '39.111389', '30.13')
('BQB', '-33.687222', '115.400278')
('YIC', '27.8033', '114.3081')
('THD', '19.90167', '105.46778')
('MJU', '-2.583333', '119.033333')
('GIU', '7.57212', '80.43412')
('BGG', '38.86111', '40.5925')
('KFS', '41.316944', '33.796111')
('DCY', '29.3231', '100.0533')
('GXH', '34.4909', '102.3719')
('CIY', '37', '14.6144')

### Grouping statements

Combines `select` and `group by` when you want aggregates by values

`select` `min(x)` ... `max()`, `sum()`, etc

`group by x`

**Task**<br>
- Which countries have the highest amount of active airlines?
- Which countries have the highest amount of inactive airlines?
- What about airports by timezones?

In [27]:
# Which countries have the highest amount of active airlines?
cursor.execute("""
SELECT 
    country, 
    count(country) AS airline_count
FROM airlines
WHERE active = 'Y'
GROUP BY 1    -- 1 = 'country' column (index = 1)
ORDER BY 2 DESC
LIMIT 10
""")
print(*cursor.fetchall(), sep='\n')

('United States', 141)
('Russia', 72)
('United Kingdom', 40)
('Germany', 37)
('Canada', 34)
('Australia', 26)
('China', 25)
('Spain', 24)
('Brazil', 23)
('France', 22)

In [28]:
# Which countries have the highest amount of inactive airports?
cursor.execute("""
SELECT 
    country, 
    count(country) AS airline_count
FROM airlines
WHERE active = 'N'
GROUP BY 1    -- 1 = 'country' column (index = 1)
ORDER BY 2 DESC
LIMIT 10
""")
print(*cursor.fetchall(), sep='\n')

('United States', 939)
('Mexico', 427)
('United Kingdom', 367)
('Canada', 284)
('Russia', 158)
('Spain', 142)
('France', 97)
('Germany', 94)
('South Africa', 81)
('Nigeria', 80)

In [31]:
# What about airports by timezones?
cursor.execute("""
SELECT 
    timezone, 
    count(*) as airport_count
FROM airports
GROUP BY timezone
ORDER BY 2 DESC
LIMIT 10
""")
print(*cursor.fetchall(), sep='\n')

('America/New_York', 628)
('America/Chicago', 373)
('Europe/Berlin', 319)
('America/Anchorage', 258)
('Europe/Paris', 232)
('America/Los_Angeles', 226)
('Asia/Chongqing', 222)
('Europe/London', 193)
('America/Toronto', 159)
('Asia/Calcutta', 141)

In [32]:
import pandas as pd
q = pd.read_sql("""
SELECT 
    timezone, 
    count(*) as airport_count
FROM airports
GROUP BY timezone
ORDER BY 2 DESC
LIMIT 10
""", con)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
# It's always a good idea to close our connections when we're done
cursor.close()
con.close()

## Goal 5: Using sql within pandas to filter

`.query()`

[query documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html)

In [1]:
# Get data for an example
import pandas as pd
shelter_data=pd.read_csv('https://data.austintexas.gov/api/views/9t4d-g238/rows.csv?accessType=DOWNLOAD')
shelter_data.dtypes

Animal ID           object
Name                object
DateTime            object
MonthYear           object
Date of Birth       object
Outcome Type        object
Outcome Subtype     object
Animal Type         object
Sex upon Outcome    object
Age upon Outcome    object
Breed               object
Color               object
dtype: object

In [2]:
max_data = shelter_data.query('Name == "Max"')
max_data.head()
#vs
shelter_data[shelter_data['Name']=="Max"]

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
24,A736717,Max,10/21/2016 02:45:00 PM,10/21/2016 02:45:00 PM,10/16/2013,Return to Owner,NaN,Dog,Neutered Male,3 years,Pug Mix,Brown Brindle
294,A688196,Max,09/16/2014 12:20:00 PM,09/16/2014 12:20:00 PM,09/16/2005,Euthanasia,Suffering,Dog,Neutered Male,9 years,Jack Russell Terrier Mix,Chocolate/White
382,A579608,Max,07/21/2014 12:43:00 PM,07/21/2014 12:43:00 PM,06/09/2010,Return to Owner,NaN,Dog,Neutered Male,4 years,Labrador Retriever Mix,Black/White
1007,A681062,Max,06/12/2014 02:22:00 PM,06/12/2014 02:22:00 PM,06/11/2011,Return to Owner,NaN,Dog,Neutered Male,3 years,Jack Russell Terrier Mix,Brown/White
1049,A727715,Max,10/07/2016 05:40:00 PM,10/07/2016 05:40:00 PM,05/25/2015,Adoption,NaN,Dog,Neutered Male,1 year,German Shepherd Mix,Tan/Black
...,...,...,...,...,...,...,...,...,...,...,...,...
111006,A773678,Max,06/14/2018 02:30:00 PM,06/14/2018 02:30:00 PM,01/04/2018,Adoption,NaN,Dog,Neutered Male,5 months,Black/Tan Hound Mix,Brown/Black
111369,A785678,Max,12/10/2018 10:15:00 PM,12/10/2018 10:15:00 PM,02/07/2018,Return to Owner,NaN,Dog,Intact Male,10 months,German Shepherd Mix,Brown/Black
111381,A777049,Max,08/02/2018 12:23:00 PM,08/02/2018 12:23:00 PM,07/22/2017,Return to Owner,NaN,Dog,Intact Male,1 year,Siberian Husky Mix,White
111971,A769530,Max,04/21/2018 07:19:00 PM,04/21/2018 07:19:00 PM,04/06/2017,Adoption,NaN,Dog,Neutered Male,1 year,Miniature Poodle Mix,White/Cream
112052,A786674,Max,01/12/2019 05:24:00 PM,01/12/2019 05:24:00 PM,12/29/2016,Adoption,NaN,Dog,Neutered Male,2 years,Australian Shepherd Mix,Red/White

In [3]:
shelter_data.rename(index=str, columns={"Animal Type": "animal_type"}, inplace = True)
test = shelter_data.query('animal_type == "Dog"')
test.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,animal_type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A720371,Moose,02/13/2016 05:59:00 PM,02/13/2016 05:59:00 PM,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
10,A740079,Terry,12/26/2016 01:45:00 PM,12/26/2016 01:45:00 PM,12/10/2013,Return to Owner,NaN,Dog,Neutered Male,3 years,Australian Cattle Dog Mix,Black/White
12,A725530,King,06/09/2016 02:50:00 PM,06/09/2016 02:50:00 PM,10/30/2015,Adoption,NaN,Dog,Neutered Male,7 months,Pit Bull Mix,Brown Brindle/White
13,A722378,Canine,03/31/2016 07:08:00 PM,03/31/2016 07:08:00 PM,03/15/2010,Return to Owner,NaN,Dog,Neutered Male,6 years,German Shepherd Mix,Brown/Black
15,A681449,Buster,07/02/2014 07:01:00 PM,07/02/2014 07:01:00 PM,06/16/2010,Return to Owner,NaN,Dog,Neutered Male,4 years,Dogo Argentino Mix,White/Brown

## Goal 6: Transfering from sqlite to pandas

In [6]:
pd_con = sqlite3.connect("flights.db")
df = pd.read_sql_query("select * from airports limit 5;", pd_con)
df

DatabaseError: Execution failed on sql 'select * from airports limit 5;': no such table: airports

**Task**: 
Convert one of the earlier queries in the lesson to a pandas data frame

In [ ]:
# Which countries have the highest amount of active airports?
df = pd.read_sql_query("""
-- your code here;
""", pd_con)
df

In [ ]:
pd_con.close()

## Integration

The [Chinook database](https://github.com/lerocha/chinook-database) is a sample database, representing a digital media store.

You need to create a query that can rank tracks in term of popularity.

The name of the database is `Chinook_Sqlite.sqlite`

Database information:<br>
- How many tables are in the database?
- What's the primary key of each table?
- What foreign keys join the tables together?
- If you had to draw a schema of how the tables are connected, what would it look like?

To answer the question:<br>
- What are the max and min dates in the Invoice table?
- What tables would you need to answer "what is your most popular track?"
- What values from each table?

In [7]:
conn = sqlite3.connect('data/Chinook_Sqlite.sqlite')
cur = conn.cursor()

In [ ]:
import pandas as pd

In [11]:
# How many tables are in the database?

# your code here
pd.read_sql("SELECT count(name) FROM sqlite_master WHERE type='table'",conn)

   count(name)
0           11

In [24]:
# What's the primary key of each table?

# your code here
cur.execute("""SELECT name FROM sqlite_master WHERE type='table'""")
results = cur.fetchall()
for row in results:
    table = row[0]
    cur.execute(f"PRAGMA table_info({table})")
    columns = cur.fetchall()
    pk = ''
    for column in columns:

        if column[5] == 1:
            pk = column[1]
    print(f'Table {table} has primary key {pk}')

print('\n --- \n')
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'",conn)
for table in tables.name:
    pk = pd.read_sql(f"PRAGMA table_info({table})",conn)
    print(f'Table {table} has primary key {pk.loc[pk.pk==1].name[0]}')

Table Album has primary key AlbumId
Table Artist has primary key ArtistId
Table Customer has primary key CustomerId
Table Employee has primary key EmployeeId
Table Genre has primary key GenreId
Table Invoice has primary key InvoiceId
Table InvoiceLine has primary key InvoiceLineId
Table MediaType has primary key MediaTypeId
Table Playlist has primary key PlaylistId
Table PlaylistTrack has primary key PlaylistId
Table Track has primary key TrackId

 ---

Table Album has primary key AlbumId
Table Artist has primary key ArtistId
Table Customer has primary key CustomerId
Table Employee has primary key EmployeeId
Table Genre has primary key GenreId
Table Invoice has primary key InvoiceId
Table InvoiceLine has primary key InvoiceLineId
Table MediaType has primary key MediaTypeId
Table Playlist has primary key PlaylistId
Table PlaylistTrack has primary key PlaylistId
Table Track has primary key TrackId

In [ ]:
# What foreign keys join the tables together?

# your code here
# hint: use "PRAGMA foreign_key_list()"

In [ ]:
# What are the max and min dates in the Invoice table?
cur.execute("""
-- your code here;
""").fetchall()

In [ ]:
# What tables would you need to answer "what is your most popular track?"

In [ ]:
# What values from each table?

In [25]:
# Put it all together:
# You need to create a query that can rank tracks in term of popularity.

results = cur.execute("""
SELECT 
    Name,
    SUM(Quantity) AS purhcase_count
From Track t
JOIN InvoiceLine il USING (TrackID)
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
;
""").fetchall()

print(*results, sep='\n')

('The Trooper', 5)
('Eruption', 4)
('Hallowed Be Thy Name', 4)
('Sure Know Something', 4)
('The Number Of The Beast', 4)
('Untitled', 4)
('2 Minutes To Midnight', 3)
('Blood Brothers', 3)
('Brasil', 3)
('Can I Play With Madness', 3)

In [ ]:
# Advanced: get the artist who sang the song!
results = cur.execute("""
-- your code here;
""").fetchall()

print(*results, sep='\n')

## Reflection

## Learning goals review:
- Goal 1: Summarize the use case for sql in the data science skill set
- Goal 2: Define key sql terminology
- Goal 3: Get information about DB schema and table structure
- Goal 4: Use basic SQL commands:
    - Construct SQL queries
    - Use JOIN to merge tables along logical columns
    - Grouping Data with SQL
- Goal 5: Query data from pandas dataframes using SQL
- Goal 6: Convert SQL to pandas

Please fill out today's [Exit Ticket](https://docs.google.com/forms/d/1O0dMGqjIV6-JIDYSIeGqTjIdep1BFiIVCc29UbEgwUM/edit)!